/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package string.opertion;

import org.junit.Test;
import static org.junit.Assert.*;

public class SpringImmutabality {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test
    public void testImmutblity() {
    	//string is immutable
    	String s= "Hello";
    	s.concat(" world");
    	assertEquals("Hello", s);
    	assertNotEquals("Hello world", s);
    	
    	//string builder is not immutable
    	StringBuilder sb= new StringBuilder("Hello");
    	sb.append(" world");
    	assertEquals("Hello world", sb.toString());
    	assertNotEquals("Hello", sb.toString());
    }
}
